package com.nichx.niplayer.designsystem.theme

import androidx.compose.ui.graphics.Color


// ═══════════════════════════
// 马卡龙（Macaron）
// ═══════════════════════════

// ── 薄荷马卡龙 Mint Macaron（薄荷绿＋奶油粉＋奶油蓝）──
internal val MintMacaronLight = Blueprint(
    primary = Color(0xFF5CBFA0),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFDDF3EB),
    onPrimaryContainer = Color(0xFF173A2F),
    secondary = Color(0xFFF2A8B8),
    onSecondary = Color(0xFF4A2530),
    secondaryContainer = Color(0xFFFCE0E6),
    onSecondaryContainer = Color(0xFF4A2530),
    tertiary = Color(0xFF8FCBE3),
    onTertiary = Color(0xFF1B3A49),
    tertiaryContainer = Color(0xFFDFF1F8),
    onTertiaryContainer = Color(0xFF1B3A49),
    inversePrimary = Color(0xFF9ADCC5),
    background = Color(0xFFF3FBF8),
    surfaceVariant = Color(0xFFE3F2EC),
    outline = Color(0xFF93A8A0),
    outlineVariant = Color(0xFFC9D8D1),
)
internal val MintMacaronDark = DarkBlueprint(
    primary = Color(0xFF8FE0C4),
    onPrimary = Color(0xFF173A2F),
    primaryContainer = Color(0xFF33846D),
    onPrimaryContainer = Color(0xFFDDF3EB),
    secondary = Color(0xFFFFC2CF),
    onSecondary = Color(0xFF4A2530),
    secondaryContainer = Color(0xFF715463),
    onSecondaryContainer = Color(0xFFFCE0E6),
    tertiary = Color(0xFFB0E1F2),
    onTertiary = Color(0xFF1B3A49),
    tertiaryContainer = Color(0xFF2E5A6E),
    onTertiaryContainer = Color(0xFFDFF1F8),
    inversePrimary = Color(0xFF5CBFA0),
    surface = Color(0xFF0F1A17),
    surfaceVariant = Color(0xFF1E302B),
    outline = Color(0xFF93A8A0),
    outlineVariant = Color(0xFF3B5049),
)

// ── 樱花马卡龙 Sakura Macaron（樱花粉＋奶油杏＋香芋紫）──
internal val SakuraMacaronLight = Blueprint(
    primary = Color(0xFFF08FB4),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFCDDE9),
    onPrimaryContainer = Color(0xFF4A2530),
    secondary = Color(0xFFF2C9A0),
    onSecondary = Color(0xFF4A3A25),
    secondaryContainer = Color(0xFFFCEBD9),
    onSecondaryContainer = Color(0xFF4A3A25),
    tertiary = Color(0xFFC5B3E8),
    onTertiary = Color(0xFF3A3560),
    tertiaryContainer = Color(0xFFEFE9FB),
    onTertiaryContainer = Color(0xFF3A3560),
    inversePrimary = Color(0xFFFFB8D2),
    background = Color(0xFFFEF4F8),
    surfaceVariant = Color(0xFFFAE8EE),
    outline = Color(0xFFAF9AA1),
    outlineVariant = Color(0xFFDCC8CF),
)
internal val SakuraMacaronDark = DarkBlueprint(
    primary = Color(0xFFFFB4D1),
    onPrimary = Color(0xFF4A2530),
    primaryContainer = Color(0xFFA05A78),
    onPrimaryContainer = Color(0xFFFCDDE9),
    secondary = Color(0xFFFFDCBA),
    onSecondary = Color(0xFF4A3A25),
    secondaryContainer = Color(0xFF7A6245),
    onSecondaryContainer = Color(0xFFFCEBD9),
    tertiary = Color(0xFFD9C9F5),
    onTertiary = Color(0xFF3A3560),
    tertiaryContainer = Color(0xFF5B5A8F),
    onTertiaryContainer = Color(0xFFEFE9FB),
    inversePrimary = Color(0xFFF08FB4),
    surface = Color(0xFF1E1018),
    surfaceVariant = Color(0xFF36222C),
    outline = Color(0xFFAF9AA1),
    outlineVariant = Color(0xFF5C4450),
)

// ── 薰衣草马卡龙 Lavender Macaron（薰衣草紫＋薄荷蓝＋紫藤）──
internal val LavenderMacaronLight = Blueprint(
    primary = Color(0xFF9290D6),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFE7E5FB),
    onPrimaryContainer = Color(0xFF2C2A4E),
    secondary = Color(0xFF8FCBE3),
    onSecondary = Color(0xFF1B3A49),
    secondaryContainer = Color(0xFFDFF1F8),
    onSecondaryContainer = Color(0xFF1B3A49),
    tertiary = Color(0xFFD6A8DC),
    onTertiary = Color(0xFF3E2A46),
    tertiaryContainer = Color(0xFFF8E7F8),
    onTertiaryContainer = Color(0xFF3E2A46),
    inversePrimary = Color(0xFFBAC2F1),
    background = Color(0xFFF6F5FC),
    surfaceVariant = Color(0xFFE9E7F6),
    outline = Color(0xFF9C99AD),
    outlineVariant = Color(0xFFCDCADB),
)
internal val LavenderMacaronDark = DarkBlueprint(
    primary = Color(0xFFB9B7F2),
    onPrimary = Color(0xFF2C2A4E),
    primaryContainer = Color(0xFF5E5C9E),
    onPrimaryContainer = Color(0xFFE7E5FB),
    secondary = Color(0xFFB0E1F2),
    onSecondary = Color(0xFF1B3A49),
    secondaryContainer = Color(0xFF2E5A6E),
    onSecondaryContainer = Color(0xFFDFF1F8),
    tertiary = Color(0xFFF0BFF6),
    onTertiary = Color(0xFF3E2A46),
    tertiaryContainer = Color(0xFF62546E),
    onTertiaryContainer = Color(0xFFF8E7F8),
    inversePrimary = Color(0xFF9290D6),
    surface = Color(0xFF151320),
    surfaceVariant = Color(0xFF272435),
    outline = Color(0xFF9C99AD),
    outlineVariant = Color(0xFF444256),
)

// ═══════════════════════════
// 莫兰迪（Morandi）
// ═══════════════════════════

// ── 杏仁慕斯 Almond Mousse（米驼＋烟粉＋灰绿）──
internal val AlmondLight = Blueprint(
    primary = Color(0xFFA99A8A),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFF0E9E0),
    onPrimaryContainer = Color(0xFF37302A),
    secondary = Color(0xFFC0A9A0),
    onSecondary = Color(0xFF40332F),
    secondaryContainer = Color(0xFFF3E8E4),
    onSecondaryContainer = Color(0xFF40332F),
    tertiary = Color(0xFFA8B0A0),
    onTertiary = Color(0xFF343932),
    tertiaryContainer = Color(0xFFE8ECE4),
    onTertiaryContainer = Color(0xFF343932),
    inversePrimary = Color(0xFFD6C8B8),
    background = Color(0xFFF8F6F2),
    surfaceVariant = Color(0xFFEFECE6),
    outline = Color(0xFFA6A09A),
    outlineVariant = Color(0xFFD4CCC5),
)
internal val AlmondDark = DarkBlueprint(
    primary = Color(0xFFD6C8B8),
    onPrimary = Color(0xFF37302A),
    primaryContainer = Color(0xFF6B5E52),
    onPrimaryContainer = Color(0xFFF0E9E0),
    secondary = Color(0xFFE0C9C0),
    onSecondary = Color(0xFF40332F),
    secondaryContainer = Color(0xFF765E58),
    onSecondaryContainer = Color(0xFFF3E8E4),
    tertiary = Color(0xFFCBD4C4),
    onTertiary = Color(0xFF343932),
    tertiaryContainer = Color(0xFF595F52),
    onTertiaryContainer = Color(0xFFE8ECE4),
    inversePrimary = Color(0xFFA99A8A),
    surface = Color(0xFF191613),
    surfaceVariant = Color(0xFF2B2621),
    outline = Color(0xFFA6A09A),
    outlineVariant = Color(0xFF4E4843),
)

// ── 灰霭紫 Grey Mauve（灰紫＋粉灰＋青灰）──
internal val MauveLight = Blueprint(
    primary = Color(0xFF9A8FA8),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFECE8F3),
    onPrimaryContainer = Color(0xFF362F40),
    secondary = Color(0xFFB5A8BE),
    onSecondary = Color(0xFF40384A),
    secondaryContainer = Color(0xFFF1EAF4),
    onSecondaryContainer = Color(0xFF40384A),
    tertiary = Color(0xFF8FA3A8),
    onTertiary = Color(0xFF343E40),
    tertiaryContainer = Color(0xFFE6EDEF),
    onTertiaryContainer = Color(0xFF343E40),
    inversePrimary = Color(0xFFCDC4D6),
    background = Color(0xFFF8F6FA),
    surfaceVariant = Color(0xFFEBE9F1),
    outline = Color(0xFFA6A0AC),
    outlineVariant = Color(0xFFD5CED9),
)
internal val MauveDark = DarkBlueprint(
    primary = Color(0xFFC4B8D2),
    onPrimary = Color(0xFF362F40),
    primaryContainer = Color(0xFF6D6176),
    onPrimaryContainer = Color(0xFFECE8F3),
    secondary = Color(0xFFD9C8DC),
    onSecondary = Color(0xFF40384A),
    secondaryContainer = Color(0xFF77616F),
    onSecondaryContainer = Color(0xFFF1EAF4),
    tertiary = Color(0xFFB5C6C9),
    onTertiary = Color(0xFF343E40),
    tertiaryContainer = Color(0xFF586D70),
    onTertiaryContainer = Color(0xFFE6EDEF),
    inversePrimary = Color(0xFF9A8FA8),
    surface = Color(0xFF161419),
    surfaceVariant = Color(0xFF29252D),
    outline = Color(0xFFA6A0AC),
    outlineVariant = Color(0xFF4B4652),
)

// ── 鼠尾草 Sage（灰绿＋沙灰＋冷灰）──
internal val SageLight = Blueprint(
    primary = Color(0xFF8A9E86),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFE6EDE2),
    onPrimaryContainer = Color(0xFF323A2E),
    secondary = Color(0xFFA8A08A),
    onSecondary = Color(0xFF403A2E),
    secondaryContainer = Color(0xFFEBE7DA),
    onSecondaryContainer = Color(0xFF403A2E),
    tertiary = Color(0xFF849AA5),
    onTertiary = Color(0xFF303C40),
    tertiaryContainer = Color(0xFFE2EAED),
    onTertiaryContainer = Color(0xFF303C40),
    inversePrimary = Color(0xFFB9CAB2),
    background = Color(0xFFF5F7F2),
    surfaceVariant = Color(0xFFE6EAE3),
    outline = Color(0xFF9CA49A),
    outlineVariant = Color(0xFFCBD0C5),
)
internal val SageDark = DarkBlueprint(
    primary = Color(0xFFB6C9B0),
    onPrimary = Color(0xFF323A2E),
    primaryContainer = Color(0xFF5E6E59),
    onPrimaryContainer = Color(0xFFE6EDE2),
    secondary = Color(0xFFC9C2AB),
    onSecondary = Color(0xFF403A2E),
    secondaryContainer = Color(0xFF6B634E),
    onSecondaryContainer = Color(0xFFEBE7DA),
    tertiary = Color(0xFFAFC2CB),
    onTertiary = Color(0xFF303C40),
    tertiaryContainer = Color(0xFF51656C),
    onTertiaryContainer = Color(0xFFE2EAED),
    inversePrimary = Color(0xFF8A9E86),
    surface = Color(0xFF141614),
    surfaceVariant = Color(0xFF262A25),
    outline = Color(0xFF9CA49A),
    outlineVariant = Color(0xFF454A43),
)

// ═══════════════════════════
// 薄荷曼波（Minty）
// ═══════════════════════════

// ── 薄荷曼波 Spearmint（薄荷绿＋桃红＋天空蓝）──
internal val SpearmintLight = Blueprint(
    primary = Color(0xFF2FBF8F),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFD2F5E8),
    onPrimaryContainer = Color(0xFF0E3327),
    secondary = Color(0xFFFF7A8A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFE0E4),
    onSecondaryContainer = Color(0xFF3A1B22),
    tertiary = Color(0xFF3FA8E8),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFD5EAFA),
    onTertiaryContainer = Color(0xFF12324A),
    inversePrimary = Color(0xFF83DDBE),
    background = Color(0xFFF0FBF6),
    surfaceVariant = Color(0xFFE2F3EC),
    outline = Color(0xFF8CA69C),
    outlineVariant = Color(0xFFC4D8CF),
)
internal val SpearmintDark = DarkBlueprint(
    primary = Color(0xFF5FE0B0),
    onPrimary = Color(0xFF0E3327),
    primaryContainer = Color(0xFF1F6A52),
    onPrimaryContainer = Color(0xFFD2F5E8),
    secondary = Color(0xFFFF9AA8),
    onSecondary = Color(0xFF3A1B22),
    secondaryContainer = Color(0xFF7C4250),
    onSecondaryContainer = Color(0xFFFFE0E4),
    tertiary = Color(0xFF6EC4F5),
    onTertiary = Color(0xFF12324A),
    tertiaryContainer = Color(0xFF29608C),
    onTertiaryContainer = Color(0xFFD5EAFA),
    inversePrimary = Color(0xFF2FBF8F),
    surface = Color(0xFF0C1613),
    surfaceVariant = Color(0xFF1B2F28),
    outline = Color(0xFF8CA69C),
    outlineVariant = Color(0xFF3B5149),
)

// ── 泡泡糖 Bubblegum（泡泡糖粉＋天空蓝＋蜜黄）──
internal val BubblegumLight = Blueprint(
    primary = Color(0xFFF26BB0),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFCDCEA),
    onPrimaryContainer = Color(0xFF4A2138),
    secondary = Color(0xFF5FC4E8),
    onSecondary = Color(0xFF143541),
    secondaryContainer = Color(0xFFD9EFF8),
    onSecondaryContainer = Color(0xFF143541),
    tertiary = Color(0xFFFFB45A),
    onTertiary = Color(0xFF4A3318),
    tertiaryContainer = Color(0xFFFDEADA),
    onTertiaryContainer = Color(0xFF4A3318),
    inversePrimary = Color(0xFFFF9CD0),
    background = Color(0xFFFEF4FA),
    surfaceVariant = Color(0xFFFAE6EF),
    outline = Color(0xFFAD96A1),
    outlineVariant = Color(0xFFDCC6D0),
)
internal val BubblegumDark = DarkBlueprint(
    primary = Color(0xFFFF8FCE),
    onPrimary = Color(0xFF4A2138),
    primaryContainer = Color(0xFFA2477E),
    onPrimaryContainer = Color(0xFFFCDCEA),
    secondary = Color(0xFF84D7F5),
    onSecondary = Color(0xFF143541),
    secondaryContainer = Color(0xFF33677A),
    onSecondaryContainer = Color(0xFFD9EFF8),
    tertiary = Color(0xFFFFD287),
    onTertiary = Color(0xFF4A3318),
    tertiaryContainer = Color(0xFF7A5A30),
    onTertiaryContainer = Color(0xFFFDEADA),
    inversePrimary = Color(0xFFF26BB0),
    surface = Color(0xFF1F1018),
    surfaceVariant = Color(0xFF38222D),
    outline = Color(0xFFAD96A1),
    outlineVariant = Color(0xFF5A4450),
)

// ── 缤纷汽水 Summer Soda（汽水橙＋苏打蓝＋汽水绿）──
internal val SummerSodaLight = Blueprint(
    primary = Color(0xFFF2873F),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFCE3CD),
    onPrimaryContainer = Color(0xFF482612),
    secondary = Color(0xFF3FB8E8),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFD7EDF8),
    onSecondaryContainer = Color(0xFF11364A),
    tertiary = Color(0xFF62C87A),
    onTertiary = Color(0xFF14301B),
    tertiaryContainer = Color(0xFFDCF1E2),
    onTertiaryContainer = Color(0xFF14301B),
    inversePrimary = Color(0xFFFFB98E),
    background = Color(0xFFFDF6F0),
    surfaceVariant = Color(0xFFF9E9DD),
    outline = Color(0xFFAC9990),
    outlineVariant = Color(0xFFD8C7BD),
)
internal val SummerSodaDark = DarkBlueprint(
    primary = Color(0xFFFFB57F),
    onPrimary = Color(0xFF482612),
    primaryContainer = Color(0xFF9C5621),
    onPrimaryContainer = Color(0xFFFCE3CD),
    secondary = Color(0xFF7FD3F5),
    onSecondary = Color(0xFF11364A),
    secondaryContainer = Color(0xFF2D5A72),
    onSecondaryContainer = Color(0xFFD7EDF8),
    tertiary = Color(0xFF99E0AA),
    onTertiary = Color(0xFF14301B),
    tertiaryContainer = Color(0xFF3B6E4A),
    onTertiaryContainer = Color(0xFFDCF1E2),
    inversePrimary = Color(0xFFF2873F),
    surface = Color(0xFF1A1310),
    surfaceVariant = Color(0xFF33251C),
    outline = Color(0xFFAC9990),
    outlineVariant = Color(0xFF57463E),
)
