package com.nichx.niplayer.designsystem.theme

import androidx.compose.ui.graphics.Color


// ═══════════════════════════
// 冷色系（Cool）
// ═══════════════════════════

// ── 雾蓝 Misty ──
internal val MistyLight = Blueprint(
    primary = Color(0xFF6E9BBB),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFDCEAF4),
    onPrimaryContainer = Color(0xFF1A3140),
    secondary = Color(0xFF8B8680),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF0EDE8),
    onSecondaryContainer = Color(0xFF2E2B27),
    tertiary = Color(0xFF7FA5A5),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFE2EFEF),
    onTertiaryContainer = Color(0xFF1E3131),
    inversePrimary = Color(0xFFB6D4EB),
    background = Color(0xFFF3F7FA),
    surfaceVariant = Color(0xFFE3EBF1),
    outline = Color(0xFF9BA6AD),
    outlineVariant = Color(0xFFC6D0D7),
)
internal val MistyDark = DarkBlueprint(
    primary = Color(0xFF9DC3DC),
    onPrimary = Color(0xFF123B57),
    primaryContainer = Color(0xFF2A5770),
    onPrimaryContainer = Color(0xFFDCEAF4),
    secondary = Color(0xFFC0B9B0),
    onSecondary = Color(0xFF2E2B27),
    secondaryContainer = Color(0xFF45423C),
    onSecondaryContainer = Color(0xFFF0EDE8),
    tertiary = Color(0xFFB4C7C7),
    onTertiary = Color(0xFF1E3131),
    tertiaryContainer = Color(0xFF364E4E),
    onTertiaryContainer = Color(0xFFE2EFEF),
    inversePrimary = Color(0xFF6E9BBB),
    surface = Color(0xFF0E1418),
    surfaceVariant = Color(0xFF1E2930),
    outline = Color(0xFF9BA6AD),
    outlineVariant = Color(0xFF3D4C54),
)

// ── 蓝莓 Blueberry（靛紫组合）──
internal val BlueberryLight = Blueprint(
    primary = Color(0xFF4A5FA5),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFDDE3F7),
    onPrimaryContainer = Color(0xFF161D3E),
    secondary = Color(0xFF7C58A6),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFEDE4F8),
    onSecondaryContainer = Color(0xFF29163C),
    tertiary = Color(0xFF4F7CC4),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFDCE8FB),
    onTertiaryContainer = Color(0xFF16263F),
    inversePrimary = Color(0xFFB4C3F0),
    background = Color(0xFFF2F4FB),
    surfaceVariant = Color(0xFFE3E7F3),
    outline = Color(0xFF949BAB),
    outlineVariant = Color(0xFFC4CBD9),
)
internal val BlueberryDark = DarkBlueprint(
    primary = Color(0xFFAEBDF6),
    onPrimary = Color(0xFF161D3E),
    primaryContainer = Color(0xFF3A4788),
    onPrimaryContainer = Color(0xFFDDE3F7),
    secondary = Color(0xFFC9A6E8),
    onSecondary = Color(0xFF29163C),
    secondaryContainer = Color(0xFF5A3B73),
    onSecondaryContainer = Color(0xFFEDE4F8),
    tertiary = Color(0xFF9DC0EF),
    onTertiary = Color(0xFF16263F),
    tertiaryContainer = Color(0xFF37517E),
    onTertiaryContainer = Color(0xFFDCE8FB),
    inversePrimary = Color(0xFF4A5FA5),
    surface = Color(0xFF10131F),
    surfaceVariant = Color(0xFF202334),
    outline = Color(0xFF949BAB),
    outlineVariant = Color(0xFF39404F),
)

// ── 湖青 Lake Cyan（湖青＋灰蓝＋铜沙）──
// 原「牛仔 Denim」：主色 #3E5F8A（色相 214°）与蓝莓 226° 仅差 12°，三支蓝扎堆；
// 2026-09-22 改为青碧（186°），补上森林 136° → 雾蓝 205° 之间的空档。持久化 key 仍为 DENIM。
internal val LakeCyanLight = Blueprint(
    primary = Color(0xFF35838C),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFD2EBEE),
    onPrimaryContainer = Color(0xFF0E343A),
    secondary = Color(0xFF5C7F99),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFDCE7F0),
    onSecondaryContainer = Color(0xFF1C2A36),
    tertiary = Color(0xFFB98250),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFF2E3CE),
    onTertiaryContainer = Color(0xFF3C2711),
    inversePrimary = Color(0xFF8FC9D2),
    background = Color(0xFFF2F7F8),
    surfaceVariant = Color(0xFFDFEAEC),
    outline = Color(0xFF8E9EA2),
    outlineVariant = Color(0xFFC2D2D5),
)
internal val LakeCyanDark = DarkBlueprint(
    primary = Color(0xFF7FC3CC),
    onPrimary = Color(0xFF0A3238),
    primaryContainer = Color(0xFF1F5A63),
    onPrimaryContainer = Color(0xFFD2EBEE),
    secondary = Color(0xFFA6C2D4),
    onSecondary = Color(0xFF12252F),
    secondaryContainer = Color(0xFF3A5468),
    onSecondaryContainer = Color(0xFFDCE7F0),
    tertiary = Color(0xFFE0AF7C),
    onTertiary = Color(0xFF3C2711),
    tertiaryContainer = Color(0xFF7A5730),
    onTertiaryContainer = Color(0xFFF2E3CE),
    inversePrimary = Color(0xFF35838C),
    surface = Color(0xFF0C1416),
    surfaceVariant = Color(0xFF1C2628),
    outline = Color(0xFF8E9EA2),
    outlineVariant = Color(0xFF38464A),
)

// ═══════════════════════════
// 暖色系（Warm）
// ═══════════════════════════

// ── 樱粉 Sakura Pink（樱粉＋奶油杏＋香芋紫）──
// 原「玫瑰 Rose」：主色 #B0686F 是低饱和砖玫瑰（色相 354°），与草莓 348° 几乎同色相，
// 且观感偏红不偏粉 —— 精简后整个色板一支粉都不剩。2026-09-22 换成本色板（沿用已删除的
// 樱花布丁 Sakura Macaron 色值，配色已调好），持久化 key 仍为 ROSE_DUST。
internal val SakuraPinkLight = Blueprint(
    primary = Color(0xFFF08FB4),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFCDDE9),
    onPrimaryContainer = Color(0xFF4A2530),
    secondary = Color(0xFFF2C9A0),
    onSecondary = Color(0xFF4A3A25),
    secondaryContainer = Color(0xFFFCEBD9),
    onSecondaryContainer = Color(0xFF4A3A25),
    tertiary = Color(0xFFC5B3E8),
    onTertiary = Color(0xFF3A3560),
    tertiaryContainer = Color(0xFFEFE9FB),
    onTertiaryContainer = Color(0xFF3A3560),
    inversePrimary = Color(0xFFFFB8D2),
    background = Color(0xFFFEF4F8),
    surfaceVariant = Color(0xFFFAE8EE),
    outline = Color(0xFFAF9AA1),
    outlineVariant = Color(0xFFDCC8CF),
)
internal val SakuraPinkDark = DarkBlueprint(
    primary = Color(0xFFFFB4D1),
    onPrimary = Color(0xFF4A2530),
    primaryContainer = Color(0xFFA05A78),
    onPrimaryContainer = Color(0xFFFCDDE9),
    secondary = Color(0xFFFFDCBA),
    onSecondary = Color(0xFF4A3A25),
    secondaryContainer = Color(0xFF7A6245),
    onSecondaryContainer = Color(0xFFFCEBD9),
    tertiary = Color(0xFFD9C9F5),
    onTertiary = Color(0xFF3A3560),
    tertiaryContainer = Color(0xFF5B5A8F),
    onTertiaryContainer = Color(0xFFEFE9FB),
    inversePrimary = Color(0xFFF08FB4),
    surface = Color(0xFF1E1018),
    surfaceVariant = Color(0xFF36222C),
    outline = Color(0xFFAF9AA1),
    outlineVariant = Color(0xFF5C4450),
)

// ── 草莓 Strawberry（草莓红＋蜜橙＋果粉）──
internal val StrawberryLight = Blueprint(
    primary = Color(0xFFF04A6A),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFDEE6),
    onPrimaryContainer = Color(0xFF4A001D),
    secondary = Color(0xFFE08A5A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFE6D8),
    onSecondaryContainer = Color(0xFF3E2310),
    tertiary = Color(0xFFD65A9E),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFFEDEF0),
    onTertiaryContainer = Color(0xFF3C0F2A),
    inversePrimary = Color(0xFFFFB1C4),
    background = Color(0xFFFEF4F6),
    surfaceVariant = Color(0xFFFBE8EE),
    outline = Color(0xFFAC949C),
    outlineVariant = Color(0xFFD9C2CA),
)
internal val StrawberryDark = DarkBlueprint(
    primary = Color(0xFFFF99AF),
    onPrimary = Color(0xFF4A001D),
    primaryContainer = Color(0xFFA32647),
    onPrimaryContainer = Color(0xFFFFDEE6),
    secondary = Color(0xFFFFB787),
    onSecondary = Color(0xFF3E2310),
    secondaryContainer = Color(0xFF8F5527),
    onSecondaryContainer = Color(0xFFFFE6D8),
    tertiary = Color(0xFFFFA3DD),
    onTertiary = Color(0xFF3C0F2A),
    tertiaryContainer = Color(0xFF8E3A6B),
    onTertiaryContainer = Color(0xFFFEDEF0),
    inversePrimary = Color(0xFFF04A6A),
    surface = Color(0xFF201019),
    surfaceVariant = Color(0xFF351F29),
    outline = Color(0xFFAC949C),
    outlineVariant = Color(0xFF5A414A),
)

// ── 珊瑚 Coral（珊瑚橙＋蜜桃）──
internal val CoralLight = Blueprint(
    primary = Color(0xFFFF6E5A),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFE2DB),
    onPrimaryContainer = Color(0xFF3D1008),
    secondary = Color(0xFFFF9B6B),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFE9DD),
    onSecondaryContainer = Color(0xFF40240F),
    tertiary = Color(0xFFD98A8A),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFFCE3E3),
    onTertiaryContainer = Color(0xFF3D1717),
    inversePrimary = Color(0xFFFFB4A8),
    background = Color(0xFFFEF4F0),
    surfaceVariant = Color(0xFFFBE8E2),
    outline = Color(0xFFAC9691),
    outlineVariant = Color(0xFFD9C6C0),
)
internal val CoralDark = DarkBlueprint(
    primary = Color(0xFFFF9A8A),
    onPrimary = Color(0xFF4A160D),
    primaryContainer = Color(0xFFB03E30),
    onPrimaryContainer = Color(0xFFFFE2DB),
    secondary = Color(0xFFFFC295),
    onSecondary = Color(0xFF40240F),
    secondaryContainer = Color(0xFF8A5124),
    onSecondaryContainer = Color(0xFFFFE9DD),
    tertiary = Color(0xFFF0BDBD),
    onTertiary = Color(0xFF3D1717),
    tertiaryContainer = Color(0xFF813A3A),
    onTertiaryContainer = Color(0xFFFCE3E3),
    inversePrimary = Color(0xFFFF6E5A),
    surface = Color(0xFF1E120E),
    surfaceVariant = Color(0xFF342520),
    outline = Color(0xFFAC9691),
    outlineVariant = Color(0xFF57433E),
)

// ═══════════════════════════
// 自然色系（Nature）
// ═══════════════════════════

// ── 森林 Forest（森绿＋灰绿＋赭棕）──
internal val ForestLight = Blueprint(
    primary = Color(0xFF3E7A4E),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFDAEEDA),
    onPrimaryContainer = Color(0xFF143114),
    secondary = Color(0xFF6B8A66),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFE4EFDF),
    onSecondaryContainer = Color(0xFF1F2C1C),
    tertiary = Color(0xFFA76B3E),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFF0DFD0),
    onTertiaryContainer = Color(0xFF37240F),
    inversePrimary = Color(0xFF9CCEAC),
    background = Color(0xFFF4F8F3),
    surfaceVariant = Color(0xFFE6EEE5),
    outline = Color(0xFF95A396),
    outlineVariant = Color(0xFFC8D4C9),
)
internal val ForestDark = DarkBlueprint(
    primary = Color(0xFF7FC98F),
    onPrimary = Color(0xFF143114),
    primaryContainer = Color(0xFF275B32),
    onPrimaryContainer = Color(0xFFDAEEDA),
    secondary = Color(0xFFB4CBAD),
    onSecondary = Color(0xFF1F2C1C),
    secondaryContainer = Color(0xFF3A4F37),
    onSecondaryContainer = Color(0xFFE4EFDF),
    tertiary = Color(0xFFE0A76B),
    onTertiary = Color(0xFF37240F),
    tertiaryContainer = Color(0xFF6E4C25),
    onTertiaryContainer = Color(0xFFF0DFD0),
    inversePrimary = Color(0xFF3E7A4E),
    surface = Color(0xFF0E1610),
    surfaceVariant = Color(0xFF1E2C21),
    outline = Color(0xFF95A396),
    outlineVariant = Color(0xFF3E5342),
)

// ── 抹茶 Matcha（抹茶绿＋麦秆黄＋藤绿）──
internal val MatchaLight = Blueprint(
    primary = Color(0xFF86A855),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFE9F2DA),
    onPrimaryContainer = Color(0xFF273616),
    secondary = Color(0xFFC8B76A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF2EDD8),
    onSecondaryContainer = Color(0xFF3C331A),
    tertiary = Color(0xFF7BA98E),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFE1EFE7),
    onTertiaryContainer = Color(0xFF1D2F26),
    inversePrimary = Color(0xFFB9D497),
    background = Color(0xFFF7F8F1),
    surfaceVariant = Color(0xFFEDF0E3),
    outline = Color(0xFFA0A494),
    outlineVariant = Color(0xFFCECFBF),
)
internal val MatchaDark = DarkBlueprint(
    primary = Color(0xFFC3DC99),
    onPrimary = Color(0xFF273616),
    primaryContainer = Color(0xFF50702E),
    onPrimaryContainer = Color(0xFFE9F2DA),
    secondary = Color(0xFFDED3A0),
    onSecondary = Color(0xFF3C331A),
    secondaryContainer = Color(0xFF71653A),
    onSecondaryContainer = Color(0xFFF2EDD8),
    tertiary = Color(0xFFBCD8C5),
    onTertiary = Color(0xFF1D2F26),
    tertiaryContainer = Color(0xFF46604F),
    onTertiaryContainer = Color(0xFFE1EFE7),
    inversePrimary = Color(0xFF86A855),
    surface = Color(0xFF151710),
    surfaceVariant = Color(0xFF25291C),
    outline = Color(0xFFA0A494),
    outlineVariant = Color(0xFF44473A),
)

// ── 焦糖 Caramel（焦糖褐＋玫瑰棕＋琥珀）──
internal val CaramelLight = Blueprint(
    primary = Color(0xFFA97949),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFF3E6D6),
    onPrimaryContainer = Color(0xFF3A2716),
    secondary = Color(0xFF9A6B8A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF0E2EC),
    onSecondaryContainer = Color(0xFF34232F),
    tertiary = Color(0xFFB08A5A),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFF1E4D4),
    onTertiaryContainer = Color(0xFF372816),
    inversePrimary = Color(0xFFE0BE96),
    background = Color(0xFFF8F3ED),
    surfaceVariant = Color(0xFFF0EAE1),
    outline = Color(0xFFA79B90),
    outlineVariant = Color(0xFFD5CAC0),
)
internal val CaramelDark = DarkBlueprint(
    primary = Color(0xFFE3C095),
    onPrimary = Color(0xFF3A2716),
    primaryContainer = Color(0xFF78572E),
    onPrimaryContainer = Color(0xFFF3E6D6),
    secondary = Color(0xFFDBB8D5),
    onSecondary = Color(0xFF34232F),
    secondaryContainer = Color(0xFF624B5D),
    onSecondaryContainer = Color(0xFFF0E2EC),
    tertiary = Color(0xFFE0BE8A),
    onTertiary = Color(0xFF372816),
    tertiaryContainer = Color(0xFF75572E),
    onTertiaryContainer = Color(0xFFF1E4D4),
    inversePrimary = Color(0xFFA97949),
    surface = Color(0xFF181310),
    surfaceVariant = Color(0xFF2C2620),
    outline = Color(0xFFA79B90),
    outlineVariant = Color(0xFF4B443C),
)
