package com.nichx.niplayer.designsystem.theme

import androidx.compose.ui.graphics.Color


// ═══════════════════════════
// 冷色系（Cool）
// ═══════════════════════════

// ── 雾蓝静谧 Misty ──
internal val MistyLight = Blueprint(
    primary = Color(0xFF6E9BBB),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFDCEAF4),
    onPrimaryContainer = Color(0xFF1A3140),
    secondary = Color(0xFF8B8680),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF0EDE8),
    onSecondaryContainer = Color(0xFF2E2B27),
    tertiary = Color(0xFF7FA5A5),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFE2EFEF),
    onTertiaryContainer = Color(0xFF1E3131),
    inversePrimary = Color(0xFFB6D4EB),
    background = Color(0xFFF3F7FA),
    surfaceVariant = Color(0xFFE3EBF1),
    outline = Color(0xFF9BA6AD),
    outlineVariant = Color(0xFFC6D0D7),
)
internal val MistyDark = DarkBlueprint(
    primary = Color(0xFF9DC3DC),
    onPrimary = Color(0xFF123B57),
    primaryContainer = Color(0xFF2A5770),
    onPrimaryContainer = Color(0xFFDCEAF4),
    secondary = Color(0xFFC0B9B0),
    onSecondary = Color(0xFF2E2B27),
    secondaryContainer = Color(0xFF45423C),
    onSecondaryContainer = Color(0xFFF0EDE8),
    tertiary = Color(0xFFB4C7C7),
    onTertiary = Color(0xFF1E3131),
    tertiaryContainer = Color(0xFF364E4E),
    onTertiaryContainer = Color(0xFFE2EFEF),
    inversePrimary = Color(0xFF6E9BBB),
    surface = Color(0xFF0E1418),
    surfaceVariant = Color(0xFF1E2930),
    outline = Color(0xFF9BA6AD),
    outlineVariant = Color(0xFF3D4C54),
)

// ── 蓝莓之夜 Blueberry Night（靛紫组合）──
internal val BlueberryLight = Blueprint(
    primary = Color(0xFF4A5FA5),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFDDE3F7),
    onPrimaryContainer = Color(0xFF161D3E),
    secondary = Color(0xFF7C58A6),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFEDE4F8),
    onSecondaryContainer = Color(0xFF29163C),
    tertiary = Color(0xFF4F7CC4),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFDCE8FB),
    onTertiaryContainer = Color(0xFF16263F),
    inversePrimary = Color(0xFFB4C3F0),
    background = Color(0xFFF2F4FB),
    surfaceVariant = Color(0xFFE3E7F3),
    outline = Color(0xFF949BAB),
    outlineVariant = Color(0xFFC4CBD9),
)
internal val BlueberryDark = DarkBlueprint(
    primary = Color(0xFFAEBDF6),
    onPrimary = Color(0xFF161D3E),
    primaryContainer = Color(0xFF3A4788),
    onPrimaryContainer = Color(0xFFDDE3F7),
    secondary = Color(0xFFC9A6E8),
    onSecondary = Color(0xFF29163C),
    secondaryContainer = Color(0xFF5A3B73),
    onSecondaryContainer = Color(0xFFEDE4F8),
    tertiary = Color(0xFF9DC0EF),
    onTertiary = Color(0xFF16263F),
    tertiaryContainer = Color(0xFF37517E),
    onTertiaryContainer = Color(0xFFDCE8FB),
    inversePrimary = Color(0xFF4A5FA5),
    surface = Color(0xFF10131F),
    surfaceVariant = Color(0xFF202334),
    outline = Color(0xFF949BAB),
    outlineVariant = Color(0xFF39404F),
)

// ── 复古牛仔 Denim（蓝＋蓝绿＋铜橙）──
internal val DenimLight = Blueprint(
    primary = Color(0xFF3E5F8A),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFD7E3F3),
    onPrimaryContainer = Color(0xFF14212F),
    secondary = Color(0xFF4E7A7A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFD6ECEC),
    onSecondaryContainer = Color(0xFF0E2424),
    tertiary = Color(0xFFB77B45),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFF0E0CC),
    onTertiaryContainer = Color(0xFF3A2613),
    inversePrimary = Color(0xFFA9C4E6),
    background = Color(0xFFF1F4F8),
    surfaceVariant = Color(0xFFE0E7EE),
    outline = Color(0xFF8F9AA8),
    outlineVariant = Color(0xFFC3CDD8),
)
internal val DenimDark = DarkBlueprint(
    primary = Color(0xFF8FB3DC),
    onPrimary = Color(0xFF14212F),
    primaryContainer = Color(0xFF2F4058),
    onPrimaryContainer = Color(0xFFD7E3F3),
    secondary = Color(0xFF7FB3B3),
    onSecondary = Color(0xFF0E2424),
    secondaryContainer = Color(0xFF2F4C4C),
    onSecondaryContainer = Color(0xFFD6ECEC),
    tertiary = Color(0xFFE0A76B),
    onTertiary = Color(0xFF3A2613),
    tertiaryContainer = Color(0xFF6E4C25),
    onTertiaryContainer = Color(0xFFF0E0CC),
    inversePrimary = Color(0xFF3E5F8A),
    surface = Color(0xFF0E1218),
    surfaceVariant = Color(0xFF1E252E),
    outline = Color(0xFF8F9AA8),
    outlineVariant = Color(0xFF39414C),
)

// ═══════════════════════════
// 暖色系（Warm）
// ═══════════════════════════

// ── 玫瑰尘埃 Rose Dust（干枯玫瑰＋灰棕）──
internal val RoseDustLight = Blueprint(
    primary = Color(0xFFB0686F),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFF6DDE0),
    onPrimaryContainer = Color(0xFF3D1A1F),
    secondary = Color(0xFF9A7B78),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF0E4E2),
    onSecondaryContainer = Color(0xFF32221F),
    tertiary = Color(0xFFB58A9A),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFF2E1E8),
    onTertiaryContainer = Color(0xFF37202B),
    inversePrimary = Color(0xFFEABCC1),
    background = Color(0xFFF9F4F3),
    surfaceVariant = Color(0xFFF0E7E6),
    outline = Color(0xFFA59796),
    outlineVariant = Color(0xFFD3C6C5),
)
internal val RoseDustDark = DarkBlueprint(
    primary = Color(0xFFE4A1A8),
    onPrimary = Color(0xFF4A2328),
    primaryContainer = Color(0xFF823E46),
    onPrimaryContainer = Color(0xFFF6DDE0),
    secondary = Color(0xFFD0B9B5),
    onSecondary = Color(0xFF32221F),
    secondaryContainer = Color(0xFF51403D),
    onSecondaryContainer = Color(0xFFF0E4E2),
    tertiary = Color(0xFFE3C2D1),
    onTertiary = Color(0xFF37202B),
    tertiaryContainer = Color(0xFF70414F),
    onTertiaryContainer = Color(0xFFF2E1E8),
    inversePrimary = Color(0xFFB0686F),
    surface = Color(0xFF1B1213),
    surfaceVariant = Color(0xFF302425),
    outline = Color(0xFFA59796),
    outlineVariant = Color(0xFF524447),
)

// ── 草莓奶油 Strawberry Cream（草莓红＋蜜橙＋果粉）──
internal val StrawberryLight = Blueprint(
    primary = Color(0xFFF04A6A),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFDEE6),
    onPrimaryContainer = Color(0xFF4A001D),
    secondary = Color(0xFFE08A5A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFE6D8),
    onSecondaryContainer = Color(0xFF3E2310),
    tertiary = Color(0xFFD65A9E),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFFEDEF0),
    onTertiaryContainer = Color(0xFF3C0F2A),
    inversePrimary = Color(0xFFFFB1C4),
    background = Color(0xFFFEF4F6),
    surfaceVariant = Color(0xFFFBE8EE),
    outline = Color(0xFFAC949C),
    outlineVariant = Color(0xFFD9C2CA),
)
internal val StrawberryDark = DarkBlueprint(
    primary = Color(0xFFFF99AF),
    onPrimary = Color(0xFF4A001D),
    primaryContainer = Color(0xFFA32647),
    onPrimaryContainer = Color(0xFFFFDEE6),
    secondary = Color(0xFFFFB787),
    onSecondary = Color(0xFF3E2310),
    secondaryContainer = Color(0xFF8F5527),
    onSecondaryContainer = Color(0xFFFFE6D8),
    tertiary = Color(0xFFFFA3DD),
    onTertiary = Color(0xFF3C0F2A),
    tertiaryContainer = Color(0xFF8E3A6B),
    onTertiaryContainer = Color(0xFFFEDEF0),
    inversePrimary = Color(0xFFF04A6A),
    surface = Color(0xFF201019),
    surfaceVariant = Color(0xFF351F29),
    outline = Color(0xFFAC949C),
    outlineVariant = Color(0xFF5A414A),
)

// ── 落日珊瑚 Sunset Coral（珊瑚橙＋蜜桃）──
internal val CoralLight = Blueprint(
    primary = Color(0xFFFF6E5A),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFE2DB),
    onPrimaryContainer = Color(0xFF3D1008),
    secondary = Color(0xFFFF9B6B),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFE9DD),
    onSecondaryContainer = Color(0xFF40240F),
    tertiary = Color(0xFFD98A8A),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFFCE3E3),
    onTertiaryContainer = Color(0xFF3D1717),
    inversePrimary = Color(0xFFFFB4A8),
    background = Color(0xFFFEF4F0),
    surfaceVariant = Color(0xFFFBE8E2),
    outline = Color(0xFFAC9691),
    outlineVariant = Color(0xFFD9C6C0),
)
internal val CoralDark = DarkBlueprint(
    primary = Color(0xFFFF9A8A),
    onPrimary = Color(0xFF4A160D),
    primaryContainer = Color(0xFFB03E30),
    onPrimaryContainer = Color(0xFFFFE2DB),
    secondary = Color(0xFFFFC295),
    onSecondary = Color(0xFF40240F),
    secondaryContainer = Color(0xFF8A5124),
    onSecondaryContainer = Color(0xFFFFE9DD),
    tertiary = Color(0xFFF0BDBD),
    onTertiary = Color(0xFF3D1717),
    tertiaryContainer = Color(0xFF813A3A),
    onTertiaryContainer = Color(0xFFFCE3E3),
    inversePrimary = Color(0xFFFF6E5A),
    surface = Color(0xFF1E120E),
    surfaceVariant = Color(0xFF342520),
    outline = Color(0xFFAC9691),
    outlineVariant = Color(0xFF57433E),
)

// ═══════════════════════════
// 自然色系（Nature）
// ═══════════════════════════

// ── 森野絮语 Forest Whispers（森绿＋灰绿＋赭棕）──
internal val ForestLight = Blueprint(
    primary = Color(0xFF3E7A4E),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFDAEEDA),
    onPrimaryContainer = Color(0xFF143114),
    secondary = Color(0xFF6B8A66),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFE4EFDF),
    onSecondaryContainer = Color(0xFF1F2C1C),
    tertiary = Color(0xFFA76B3E),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFF0DFD0),
    onTertiaryContainer = Color(0xFF37240F),
    inversePrimary = Color(0xFF9CCEAC),
    background = Color(0xFFF4F8F3),
    surfaceVariant = Color(0xFFE6EEE5),
    outline = Color(0xFF95A396),
    outlineVariant = Color(0xFFC8D4C9),
)
internal val ForestDark = DarkBlueprint(
    primary = Color(0xFF7FC98F),
    onPrimary = Color(0xFF143114),
    primaryContainer = Color(0xFF275B32),
    onPrimaryContainer = Color(0xFFDAEEDA),
    secondary = Color(0xFFB4CBAD),
    onSecondary = Color(0xFF1F2C1C),
    secondaryContainer = Color(0xFF3A4F37),
    onSecondaryContainer = Color(0xFFE4EFDF),
    tertiary = Color(0xFFE0A76B),
    onTertiary = Color(0xFF37240F),
    tertiaryContainer = Color(0xFF6E4C25),
    onTertiaryContainer = Color(0xFFF0DFD0),
    inversePrimary = Color(0xFF3E7A4E),
    surface = Color(0xFF0E1610),
    surfaceVariant = Color(0xFF1E2C21),
    outline = Color(0xFF95A396),
    outlineVariant = Color(0xFF3E5342),
)

// ── 抹茶微风 Matcha Breeze（抹茶绿＋麦秆黄＋藤绿）──
internal val MatchaLight = Blueprint(
    primary = Color(0xFF86A855),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFE9F2DA),
    onPrimaryContainer = Color(0xFF273616),
    secondary = Color(0xFFC8B76A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF2EDD8),
    onSecondaryContainer = Color(0xFF3C331A),
    tertiary = Color(0xFF7BA98E),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFE1EFE7),
    onTertiaryContainer = Color(0xFF1D2F26),
    inversePrimary = Color(0xFFB9D497),
    background = Color(0xFFF7F8F1),
    surfaceVariant = Color(0xFFEDF0E3),
    outline = Color(0xFFA0A494),
    outlineVariant = Color(0xFFCECFBF),
)
internal val MatchaDark = DarkBlueprint(
    primary = Color(0xFFC3DC99),
    onPrimary = Color(0xFF273616),
    primaryContainer = Color(0xFF50702E),
    onPrimaryContainer = Color(0xFFE9F2DA),
    secondary = Color(0xFFDED3A0),
    onSecondary = Color(0xFF3C331A),
    secondaryContainer = Color(0xFF71653A),
    onSecondaryContainer = Color(0xFFF2EDD8),
    tertiary = Color(0xFFBCD8C5),
    onTertiary = Color(0xFF1D2F26),
    tertiaryContainer = Color(0xFF46604F),
    onTertiaryContainer = Color(0xFFE1EFE7),
    inversePrimary = Color(0xFF86A855),
    surface = Color(0xFF151710),
    surfaceVariant = Color(0xFF25291C),
    outline = Color(0xFFA0A494),
    outlineVariant = Color(0xFF44473A),
)

// ── 焦糖琥珀 Caramel Amber（焦糖褐＋玫瑰棕＋琥珀）──
internal val CaramelLight = Blueprint(
    primary = Color(0xFFA97949),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFF3E6D6),
    onPrimaryContainer = Color(0xFF3A2716),
    secondary = Color(0xFF9A6B8A),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF0E2EC),
    onSecondaryContainer = Color(0xFF34232F),
    tertiary = Color(0xFFB08A5A),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFF1E4D4),
    onTertiaryContainer = Color(0xFF372816),
    inversePrimary = Color(0xFFE0BE96),
    background = Color(0xFFF8F3ED),
    surfaceVariant = Color(0xFFF0EAE1),
    outline = Color(0xFFA79B90),
    outlineVariant = Color(0xFFD5CAC0),
)
internal val CaramelDark = DarkBlueprint(
    primary = Color(0xFFE3C095),
    onPrimary = Color(0xFF3A2716),
    primaryContainer = Color(0xFF78572E),
    onPrimaryContainer = Color(0xFFF3E6D6),
    secondary = Color(0xFFDBB8D5),
    onSecondary = Color(0xFF34232F),
    secondaryContainer = Color(0xFF624B5D),
    onSecondaryContainer = Color(0xFFF0E2EC),
    tertiary = Color(0xFFE0BE8A),
    onTertiary = Color(0xFF372816),
    tertiaryContainer = Color(0xFF75572E),
    onTertiaryContainer = Color(0xFFF1E4D4),
    inversePrimary = Color(0xFFA97949),
    surface = Color(0xFF181310),
    surfaceVariant = Color(0xFF2C2620),
    outline = Color(0xFFA79B90),
    outlineVariant = Color(0xFF4B443C),
)
